set -e

echo "Setting up the users"
WWG_PASSWORD=$(tr -d '\r' < /run/secrets/pg_password)
psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER << EOF
SET CLIENT_ENCODING TO utf8;
DO \$\$
BEGIN
    CREATE USER $WWG_USER;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE '$WWG_USER already exists';
END \$\$;
ALTER ROLE $WWG_USER PASSWORD '$WWG_PASSWORD';
ALTER ROLE $WWG_USER SET search_path TO $SEARCH_PATH;
DROP DATABASE IF EXISTS $POSTGRES_DB;
CREATE DATABASE $POSTGRES_DB;
GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $WWG_USER;
EOF
