#!/bin/bash
set -e

echo "Setting up the users"
psql -v ON_ERROR_STOP=1 -U $POSTGRES_USER << EOF
SET CLIENT_ENCODING TO utf8;
DO \$\$
BEGIN
    CREATE USER $WWG_USER;
EXCEPTION WHEN duplicate_object THEN
    RAISE NOTICE '$WWG_USER already exists';
END \$\$;
ALTER ROLE $WWG_USER PASSWORD '$WWG_PASSWORD';
ALTER ROLE $WWG_USER SET search_path TO $SEARCH_PATH;
DROP DATABASE IF EXISTS $DB_NAME;
CREATE DATABASE $DB_NAME;
GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $WWG_USER;
EOF