\encoding 'UTF8';
CREATE SCHEMA wwg AUTHORIZATION wwgadmin;

CREATE EXTENSION fuzzystrmatch
    SCHEMA wwg
    VERSION "1.1";

CREATE EXTENSION pg_trgm
    SCHEMA wwg
    VERSION "1.5";

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA wwg TO wwgadmin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA wwg TO wwgadmin;
